### ISSUE TITLE
why pip in entrypoint?

### ISSUE THREAD

**Issue by obarisk** [fenglc/dockercloud-pgadmin4#12]
In entrypoint, line 57
pip install flask_htmlmin

why not pip it in docker file but in entrypoint?
Is there any reason?

**Comment by fenglc** [comment]
no special reason
both are ok.

**Comment by obarisk** [comment]
Thanks,

But pip doesn't work in some limit network environment, 
In such situation, it's imposible to start the container.

**Comment by fenglc** [comment]
fixed it
